### ISSUE TITLE
关于 『手机端编译安卓内核』

### ISSUE THREAD

**Issue by jiang3231634** [zixijian/zixijian.github.io#1]
您好，想请教个问题：
根据您这个教程，在tc-build那一步，LLVM stage1经常出现窗口自动关闭，也没有提示
试了很多次通过了stage1，到stage2的时候又经常性自动关闭了，总共5千多，大概到一千多的时候就会关闭，
重新打开也不会接着上一次的继续编译要重新开始。。。。
请问我可以怎么解决这个问题吗？

**Comment by zixijian** [comment]
> 您好，想请教个问题： 根据您这个教程，在tc-build那一步，LLVM stage1经常出现窗口自动关闭，也没有提示 试了很多次通过了stage1，到stage2的时候又经常性自动关闭了，总共5千多，大概到一千多的时候就会关闭， 重新打开也不会接着上一次的继续编译要重新开始。。。。 请问我可以怎么解决这个问题吗？

直接使用预编译的clang版本，tbl编译失败一般是网络问题，连接git不稳定。
